import StyledJsxRegistry from "./lib/registry";
import GlobalStyles from "./lib/global";

export const metadata = {
  title: "Todd Productions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GlobalStyles />
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
