export { default as ContactTemplate } from "./ContactTemplate/ContactTemplate"
export { default as HomeTemplate } from "./HomeTemplate/HomeTemplate"
export { default as SEOTemplate } from "./SEOTemplate/SEOTemplate"
export { default as ServiceTemplate } from "./ServiceTemplate/ServiceTemplate"
export { default as SamplesTemplate } from "./SamplesTemplate/SamplesTemplate"
export { default as BasicTemplate } from "./BasicTemplate/BasicTemplate"
