export { default as CategoryTemplate } from "./CategoryTemplate/CategoryTemplate"
export { default as ContactTemplate } from "./ContactTemplate/ContactTemplate"
export { default as HomeTemplate } from "./HomeTemplate/HomeTemplate"
export { default as SEOTemplate } from "./SEOTemplate/SEOTemplate"
export { default as ServiceTemplate } from "./ServiceTemplate/ServiceTemplate"
